"""Init DB

Revision ID: 12ae92657f7b
Revises: 
Create Date: 2026-01-15 14:09:38.292942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12ae92657f7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('domain_url', sa.String(length=255), nullable=True),
    sa.Column('company_name_en', sa.String(length=200), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('positive_keywords', sa.JSON(), nullable=True),
    sa.Column('negative_keywords', sa.JSON(), nullable=True),
    sa.Column('ceo_name', sa.String(length=100), nullable=True),
    sa.Column('main_services', sa.String(length=500), nullable=True),
    sa.Column('search_strategy', sa.String(length=50), nullable=True),
    sa.Column('crawling_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_table('esg_service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=10), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('category_name_en', sa.String(length=200), nullable=True),
    sa.Column('main_topic', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_service_categories_category_code'), 'esg_service_categories', ['category_code'], unique=True)
    op.create_index(op.f('ix_esg_service_categories_created_at'), 'esg_service_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_esg_service_categories_id'), 'esg_service_categories', ['id'], unique=False)
    op.create_index(op.f('ix_esg_service_categories_main_topic'), 'esg_service_categories', ['main_topic'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('article_url', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_url')
    )
    op.create_index(op.f('ix_articles_company_id'), 'articles', ['company_id'], unique=False)
    op.create_index(op.f('ix_articles_created_at'), 'articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_table('company_service_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('provides_service', sa.Boolean(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['esg_service_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'category_id', name='uq_company_service_mapping')
    )
    op.create_index(op.f('ix_company_service_mappings_category_id'), 'company_service_mappings', ['category_id'], unique=False)
    op.create_index(op.f('ix_company_service_mappings_company_id'), 'company_service_mappings', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_service_mappings_created_at'), 'company_service_mappings', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_service_mappings_id'), 'company_service_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_company_service_mappings_provides_service'), 'company_service_mappings', ['provides_service'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_is_public'), 'documents', ['is_public'], unique=False)
    op.create_index(op.f('ix_documents_is_template'), 'documents', ['is_template'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('mention_trends_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_mention_trends_daily_company_date')
    )
    op.create_index('idx_mention_trends_daily_company_date', 'mention_trends_daily', ['company_id', 'date'], unique=False)
    op.create_index(op.f('ix_mention_trends_daily_company_id'), 'mention_trends_daily', ['company_id'], unique=False)
    op.create_index(op.f('ix_mention_trends_daily_created_at'), 'mention_trends_daily', ['created_at'], unique=False)
    op.create_index(op.f('ix_mention_trends_daily_date'), 'mention_trends_daily', ['date'], unique=False)
    op.create_index(op.f('ix_mention_trends_daily_id'), 'mention_trends_daily', ['id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_auto_saved', sa.Boolean(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sections_count', sa.Integer(), nullable=True),
    sa.Column('blocks_count', sa.Integer(), nullable=True),
    sa.Column('chars_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_version_number')
    )
    op.create_index('idx_document_versions_document_created', 'document_versions', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_document_versions_author_id'), 'document_versions', ['author_id'], unique=False)
    op.create_index(op.f('ix_document_versions_created_at'), 'document_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_id'), 'document_versions', ['id'], unique=False)
    op.create_index(op.f('ix_document_versions_is_auto_saved'), 'document_versions', ['is_auto_saved'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gri_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_created_at'), 'sections', ['created_at'], unique=False)
    op.create_index(op.f('ix_sections_document_id'), 'sections', ['document_id'], unique=False)
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_document_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_created_at'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_document_versions_is_auto_saved'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_created_at'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_author_id'), table_name='document_versions')
    op.drop_index('idx_document_versions_document_created', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_mention_trends_daily_id'), table_name='mention_trends_daily')
    op.drop_index(op.f('ix_mention_trends_daily_date'), table_name='mention_trends_daily')
    op.drop_index(op.f('ix_mention_trends_daily_created_at'), table_name='mention_trends_daily')
    op.drop_index(op.f('ix_mention_trends_daily_company_id'), table_name='mention_trends_daily')
    op.drop_index('idx_mention_trends_daily_company_date', table_name='mention_trends_daily')
    op.drop_table('mention_trends_daily')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_template'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_public'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_company_service_mappings_provides_service'), table_name='company_service_mappings')
    op.drop_index(op.f('ix_company_service_mappings_id'), table_name='company_service_mappings')
    op.drop_index(op.f('ix_company_service_mappings_created_at'), table_name='company_service_mappings')
    op.drop_index(op.f('ix_company_service_mappings_company_id'), table_name='company_service_mappings')
    op.drop_index(op.f('ix_company_service_mappings_category_id'), table_name='company_service_mappings')
    op.drop_table('company_service_mappings')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_created_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_company_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_esg_service_categories_main_topic'), table_name='esg_service_categories')
    op.drop_index(op.f('ix_esg_service_categories_id'), table_name='esg_service_categories')
    op.drop_index(op.f('ix_esg_service_categories_created_at'), table_name='esg_service_categories')
    op.drop_index(op.f('ix_esg_service_categories_category_code'), table_name='esg_service_categories')
    op.drop_table('esg_service_categories')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
