"""add documents chapters sections tables

Revision ID: af493c0cf893
Revises: 191edbe4b4f9
Create Date: 2025-10-03 23:01:03.608451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af493c0cf893'
down_revision: Union[str, Sequence[str], None] = '191edbe4b4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_search_strategy'), table_name='companies')
    op.drop_index(op.f('idx_company_service_mappings_category'), table_name='company_service_mappings')
    op.drop_index(op.f('idx_company_service_mappings_company'), table_name='company_service_mappings')
    op.drop_index(op.f('idx_company_service_mappings_provides'), table_name='company_service_mappings')
    op.create_index(op.f('ix_company_service_mappings_category_id'), 'company_service_mappings', ['category_id'], unique=False)
    op.create_index(op.f('ix_company_service_mappings_company_id'), 'company_service_mappings', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_service_mappings_id'), 'company_service_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_company_service_mappings_provides_service'), 'company_service_mappings', ['provides_service'], unique=False)
    op.drop_index(op.f('idx_esg_service_categories_code'), table_name='esg_service_categories')
    op.drop_index(op.f('idx_esg_service_categories_topic'), table_name='esg_service_categories')
    op.drop_constraint(op.f('uq_esg_service_categories_code'), 'esg_service_categories', type_='unique')
    op.create_index(op.f('ix_esg_service_categories_category_code'), 'esg_service_categories', ['category_code'], unique=True)
    op.create_index(op.f('ix_esg_service_categories_id'), 'esg_service_categories', ['id'], unique=False)
    op.create_index(op.f('ix_esg_service_categories_main_topic'), 'esg_service_categories', ['main_topic'], unique=False)
    op.drop_index(op.f('idx_events_category'), table_name='events')
    op.drop_index(op.f('idx_events_id'), table_name='events')
    op.drop_index(op.f('idx_events_start_date'), table_name='events')
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.drop_index(op.f('idx_mention_trends_daily_date'), table_name='mention_trends_daily')
    op.create_index(op.f('ix_mention_trends_daily_company_id'), 'mention_trends_daily', ['company_id'], unique=False)
    op.create_index(op.f('ix_mention_trends_daily_date'), 'mention_trends_daily', ['date'], unique=False)
    op.create_index(op.f('ix_mention_trends_daily_id'), 'mention_trends_daily', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mention_trends_daily_id'), table_name='mention_trends_daily')
    op.drop_index(op.f('ix_mention_trends_daily_date'), table_name='mention_trends_daily')
    op.drop_index(op.f('ix_mention_trends_daily_company_id'), table_name='mention_trends_daily')
    op.create_index(op.f('idx_mention_trends_daily_date'), 'mention_trends_daily', ['date'], unique=False)
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.create_index(op.f('idx_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('idx_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('idx_events_category'), 'events', ['category'], unique=False)
    op.drop_index(op.f('ix_esg_service_categories_main_topic'), table_name='esg_service_categories')
    op.drop_index(op.f('ix_esg_service_categories_id'), table_name='esg_service_categories')
    op.drop_index(op.f('ix_esg_service_categories_category_code'), table_name='esg_service_categories')
    op.create_unique_constraint(op.f('uq_esg_service_categories_code'), 'esg_service_categories', ['category_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_esg_service_categories_topic'), 'esg_service_categories', ['main_topic'], unique=False)
    op.create_index(op.f('idx_esg_service_categories_code'), 'esg_service_categories', ['category_code'], unique=False)
    op.drop_index(op.f('ix_company_service_mappings_provides_service'), table_name='company_service_mappings')
    op.drop_index(op.f('ix_company_service_mappings_id'), table_name='company_service_mappings')
    op.drop_index(op.f('ix_company_service_mappings_company_id'), table_name='company_service_mappings')
    op.drop_index(op.f('ix_company_service_mappings_category_id'), table_name='company_service_mappings')
    op.create_index(op.f('idx_company_service_mappings_provides'), 'company_service_mappings', ['provides_service'], unique=False)
    op.create_index(op.f('idx_company_service_mappings_company'), 'company_service_mappings', ['company_id'], unique=False)
    op.create_index(op.f('idx_company_service_mappings_category'), 'company_service_mappings', ['category_id'], unique=False)
    op.create_index(op.f('ix_companies_search_strategy'), 'companies', ['search_strategy'], unique=False)
    # ### end Alembic commands ###
